{
 "title": "Poller Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Consumer Kafka Calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "requests_latency_seconds_poller_consumer_count"
    }
   ]
  },
  {
   "title": "Producer Kafka Calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "requests_latency_seconds_poller_publish_sum"
    }
   ]
  },
  {
   "title": "Consume Watch Counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "consume_watch" }
   ]
  },
  {
   "title": "Produce Weather Counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "publish_weather" }
   ]
  }
 ]
}