{
 "title": "Webapp Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests made to the application",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(create_user) + sum(create_watch) + sum(update_user_info) + sum(update_watch) + sum(get_all_watches) + sum(get_user_info) + sum(get_user_info_by_ID) + sum(delete_watch) + sum(get_watch_by_ID)"
    }
   ]
  },
  {
   "title": "Create User Counter",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "create_user" }
   ]
  },
  {
   "title": "Total Counts to Create User API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(create_user)" }
   ]
  },
  {
   "title": "Get User Info by ID",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "get_user_info_by_ID" }
   ]
  },
  {
   "title": "Total Count of Get User By ID API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(get_user_info_by_ID)" }
   ]
  },
  {
   "title": "Update User Info",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "update_user_info" }
   ]
  },
  {
   "title": "Total Count of Update user info API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(update_user_info)" }
   ]
  },
  {
   "title": "Get User Info Counter",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "get_user_info" }
   ]
  },
  {
   "title": "Total Count of Get User Info API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(get_user_info)" }
   ]
  },
  {
   "title": "Create Watch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "create_watch" }
   ]
  },
  {
   "title": "Total Count of Create Watch API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(create_watch)" }
   ]
  },
  {
   "title": "Get Watch By ID",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "get_watch_by_ID" }
   ]
  },
  {
   "title": "Total Count of Get Watch By ID API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(get_watch_by_ID)" }
   ]
  },
  {
   "title": "Update Watch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "update_watch" }
   ]
  },
  {
   "title": "Total Count of Update Watch API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(update_watch)" }
   ]
  },
  {
   "title": "Delete Watch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "delete_watch" }
   ]
  },
  {
   "title": "Total Count of Delete Watch API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(delete_watch)" }
   ]
  },
  {
   "title": "Get All Watches",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "get_all_watches" }
   ]
  },
  {
   "title": "Total Count of Get All Watches API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(get_all_watches)" }
   ]
  },
  {
   "title": "User DB Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "requests_latency_seconds_user_count"
    }
   ]
  },
  {
   "title": "Watch DB Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "requests_latency_seconds_watch_count"
    }
   ]
  },
  {
   "title": "Kafka Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "requests_latency_seconds_kafka_count"
    }
   ]
  },
  {
   "title": "Alert DB Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "requests_latency_seconds_alert_count"
    }
   ]
  }
 ]
}